export const GAME_ACTIONS = {
    ADD_WORD: "ADD_WORD",

    SET_ERROR: "SET_ERROR",

    RESET_ERROR: "RESET_ERROR",

    RESET_GAME: "RESET_GAME",

    SET_STATUS: "SET_STATUS",

    TICK: "TICK",

    FINISH_GAME: "FINISH_GAME",

    START_SUBMIT: "START_SUBMIT",
    
    END_SUBMIT: "END_SUBMIT",
};