export const GAME_ACTIONS = {
    ADD_WORD: "ADD_WORD",

    SET_ERROR: "SET_ERROR",

    RESET_ERROR: "RESET_ERROR",

    START_COUNTDOWN: "START_COUNTDOWN",

    TICK: "TICK",

    START_GAME: "START_GAME",

    FINISH_GAME: "FINISH_GAME",

    START_SUBMIT: "START_SUBMIT",
    
    END_SUBMIT: "END_SUBMIT",
};